server:
  port: 8081
  servlet:
    context-path: /spring-graphql
spring:
  application:
    name: spring-graphql
  graphql:
    graphiql:
      enabled: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: password
      database: book
      authentication-database: admin