server:
  port: 8080
  servlet:
    context-path: /spring-graphql
spring:
  application:
    name: spring-graphql
  graphql:
    graphiql:
      enabled: true
  data:
    mongodb:
      uri: mongodb+srv://user:password@study.7wuod59.mongodb.net
      database: book